import Link from "next/link";
import "~/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const pages = {
  "/": "Home",
  "/prisma": "Prisma",
  "/drizzle": "Drizzle",
  "/planetscale": "Planetscale",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-slate-800 text-white">
          <ul className="flex gap-5">
            {Object.entries(pages).map(([path, title]) => (
              <li key={path}>
                <Link
                  href={path}
                  className="block p-4 transition-colors hover:bg-slate-900"
                >
                  {title}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
